#!/bin/bash

chmod 0755 /taig/taig

#mkdir /Library/NanoLaunchDaemons#mv /System/Library/NanoLaunchDaemons/* /Library/NanoLaunchDaemons/

mkdir /etc/rc.d
ln -s /usr/libexec/substrate /etc/rc.d/substrate

declare -a cydia
cydia=($CYDIA)
firmware=$(sw_vers -productVersion)

if [[ ${CYDIA+@} ]]; then
   eval "echo 'finish:reboot' >&${cydia[0]}"
fi

echo
